mongo:
    image: mongo
    user: mongodb
back:
    build: ./back
    volumes:
        - ./back:/usr/app/back
        - /usr/app/back/node_modules
    links:
        - mongo
    ports:
        - "9229:9229"
        - "3000:3000"
front:
    build: ./front
    volumes:
        - ./front:/usr/app/front
        - /usr/app/front/node_modules
    links:
        - mongo
    ports:
        - "4200:4200"
nginx:
    build: ./nginx
    links:
        - back:back
        - front:front
    ports:
        - "80:80"