mongo:
    image: mongo
back:
    build: ./back
    volumes:
      - ./back:/usr/app/back
      - ./business:/usr/app/business
    links:
        - mongo
    ports:
        - "9229:9229"
front:
    build: ./front
    volumes:
      - ./front:/usr/app/front
      - ./business:/usr/app/business
    links:
        - mongo
nginx:
    build: ./nginx
    links:
        - back:back
        - front:front
    ports:
        - "80:80"